"""Declarative modelling workflow: Project spec → prep → explore → run → export.

This is the GUI-agnostic engine behind the workbench (``easy_glm.app``); every
function here is usable from plain Python as well.
"""

from .diagnostics import (
    ae_by_pair,
    ae_by_variable,
    alpha_path,
    base_rate_change,
    describe_diff,
    deviance_stats,
    double_lift,
    expected_claims,
    gini,
    lift_table,
    model_metrics,
    pearson_dispersion,
    rate_model_diff,
    relativity_diff,
    residual_factor_search,
    residual_pair_search,
    snapshot_diff,
    totals,
    unit_values,
)
from .explore import leakage_report, single_factor_strength, univariate
from .export import to_script
from .prep import (
    add_split_column,
    apply_variables,
    column_summary,
    eval_expr,
    infer_source_type,
    load_source,
    prepare,
    train_holdout,
)
from .project import (
    Adjustment,
    DataConfig,
    DataSource,
    Derived,
    DesignConfig,
    DesignDefaults,
    Interaction,
    ModelConfig,
    Penalty,
    Project,
    Recode,
    Split,
    TableSnapshot,
    VariableDesign,
)
from .report import to_report_html
from .run import (
    AdjustmentError,
    ModelRun,
    UnusableColumnError,
    apply_adjustments,
    build_design,
    encoder_for,
    exposure_for,
    missing_variables,
    monotone_for,
    rate_model_for,
    rebalance_override,
    rebuild_rate_model,
    run_model,
)

__all__ = [
    "Project",
    "DataConfig",
    "DataSource",
    "Recode",
    "Derived",
    "Split",
    "DesignConfig",
    "DesignDefaults",
    "VariableDesign",
    "ModelConfig",
    "Penalty",
    "Adjustment",
    "TableSnapshot",
    "Interaction",
    "load_source",
    "infer_source_type",
    "eval_expr",
    "apply_variables",
    "add_split_column",
    "train_holdout",
    "prepare",
    "column_summary",
    "univariate",
    "leakage_report",
    "single_factor_strength",
    "build_design",
    "encoder_for",
    "monotone_for",
    "run_model",
    "AdjustmentError",
    "apply_adjustments",
    "UnusableColumnError",
    "rebuild_rate_model",
    "rate_model_for",
    "rebalance_override",
    "missing_variables",
    "exposure_for",
    "ModelRun",
    "totals",
    "unit_values",
    "deviance_stats",
    "lift_table",
    "gini",
    "double_lift",
    "expected_claims",
    "ae_by_variable",
    "ae_by_pair",
    "residual_factor_search",
    "residual_pair_search",
    "relativity_diff",
    "rate_model_diff",
    "snapshot_diff",
    "base_rate_change",
    "describe_diff",
    "pearson_dispersion",
    "alpha_path",
    "model_metrics",
    "to_script",
    "to_report_html",
]
