"""Render a :class:`Project` (and a fitted run) as a standalone Python script."""

from __future__ import annotations

from typing import Any

from easy_glm.core.design import CategoricalEncoder, DesignSpec, StepEncoder

from .project import ModelConfig, Project
from .run import ModelRun


def _lit(value: Any) -> str:
    """Python literal for knots / levels / scalars."""
    if isinstance(value, float) and value.is_integer():
        return str(int(value)) if abs(value) < 1e15 else repr(value)
    return repr(value)


def _list(values: list[Any], indent: int = 8, width: int = 88) -> str:
    items = [_lit(v) for v in values]
    one_line = "[" + ", ".join(items) + "]"
    if len(one_line) + indent <= width:
        return one_line
    pad = " " * indent
    lines, cur = [], pad
    for it in items:
        if len(cur) + len(it) + 2 > width:
            lines.append(cur.rstrip())
            cur = pad
        cur += it + ", "
    lines.append(cur.rstrip())
    return "[\n" + "\n".join(lines) + "\n" + " " * (indent - 4) + "]"


def _spec_code(spec: DesignSpec) -> str:
    parts = []
    for var, enc in spec.encoders.items():
        if isinstance(enc, StepEncoder):
            parts.append(
                f"    {var!r}: StepEncoder({var!r}, {_list(enc.knots)}, null_indicator={enc.null_indicator}),"
            )
        else:
            assert isinstance(enc, CategoricalEncoder)
            parts.append(
                f"    {var!r}: CategoricalEncoder({var!r}, {_list(enc.levels)}),"
            )
    return "spec = DesignSpec({\n" + "\n".join(parts) + "\n})"


def _load_code(project: Project) -> list[str]:
    src = project.data.source
    opts = ", ".join(f"{k}={v!r}" for k, v in src.options.items())
    opts = (", " + opts) if opts else ""
    kind = src.type.lower()
    if kind == "parquet":
        return [f"df = pl.read_parquet({src.path!r}{opts})"]
    if kind == "csv":
        return [f"df = pl.read_csv({src.path!r}{opts})"]
    if kind in ("ipc", "arrow", "feather"):
        return [f"df = pl.read_ipc({src.path!r}{opts})"]
    if kind in ("xlsx", "excel"):
        return [f"df = pl.read_excel({src.path!r}{opts})"]
    if kind == "sas7bdat":
        enc = src.options.get("encoding", "latin-1")
        return [f"df = pl.from_pandas(pd.read_sas({src.path!r}, encoding={enc!r}))"]
    raise ValueError(f"Unsupported source type {src.type!r}")


def _fit_code(
    cfg: ModelConfig, alpha: float, monotone: dict[str, str], chose_by_cv: bool
) -> str:
    args = [
        "train",
        "spec",
        repr(cfg.target),
        f"family={cfg.family!r}",
    ]
    if cfg.link:
        args.append(f"link={cfg.link!r}")
    if cfg.weight:
        args.append(f"weight_col={cfg.weight!r}")
    if cfg.offset:
        args.append(f"offset_col={cfg.offset!r}")
    if cfg.divide_target_by_weight:
        args.append("divide_target_by_weight=True")
    args.append(f"alpha={alpha!r}")
    if cfg.penalty.l1_ratio != 1.0:
        args.append(f"l1_ratio={cfg.penalty.l1_ratio!r}")
    if monotone:
        args.append(f"monotone={monotone!r}")
    comment = ""
    if chose_by_cv:
        comment = (
            f"# alpha was chosen by {cfg.penalty.cv}-fold CV over {cfg.penalty.n_alphas} "
            "alphas in the workbench; it is written out so this script is deterministic.\n"
        )
    return comment + "fit = fit_glm(\n    " + ",\n    ".join(args) + ",\n)"


def to_script(
    project: Project,
    model: str | None = None,
    *,
    run: ModelRun | None = None,
    output_prefix: str | None = None,
) -> str:
    """Python source reproducing ``project.models[model]`` with the public API.

    With a fitted ``run`` the design is written out explicitly (every knot and
    level) and the resolved alpha is used, so the script is self-contained and
    deterministic. Without a run the design is derived from the data at run
    time and CV (if configured) is re-run.
    """
    model = model or project.champion or next(iter(project.models), None)
    if model is None or model not in project.models:
        raise ValueError("No model to export")
    cfg = project.models[model]
    d = project.data
    prefix = output_prefix or model
    uses_sas = d.source.type.lower() == "sas7bdat"

    lines: list[str] = [
        f'"""{project.name} — model {model!r}: generated by easy_glm workbench.',
        "",
        "Re-run this file to rebuild the model, its rate tables and the .easyglm scorer.",
        '"""',
        "",
        "import numpy as np",
        "import polars as pl",
    ]
    if uses_sas:
        lines.append("import pandas as pd")
    lines += [
        "",
        "from easy_glm import (",
        "    CategoricalEncoder,",
        "    DesignSpec,",
        "    StepEncoder,",
        "    fit_glm,",
        "    to_rate_model,",
        ")",
        "",
        "# ---------------------------------------------------------------- 1. data",
        *_load_code(project),
    ]
    if d.renames:
        lines.append(f"df = df.rename({d.renames!r})")
    for col, rc in d.recodes.items():
        default = (
            f"pl.col({col!r}).cast(pl.Utf8)" if rc.default is None else repr(rc.default)
        )
        if rc.mapping:
            lines += [
                "df = df.with_columns(",
                f"    pl.col({col!r}).cast(pl.Utf8).replace_strict(",
                f"        {rc.mapping!r},",
                f"        default={default}, return_dtype=pl.Utf8,",
                f"    ).alias({col!r})",
                ")",
            ]
        else:
            lines.append(f"df = df.with_columns(pl.col({col!r}).cast(pl.Utf8))")
    for col, kind in d.types.items():
        cast = "pl.Utf8" if kind == "categorical" else "pl.Float64, strict=False"
        lines.append(f"df = df.with_columns(pl.col({col!r}).cast({cast}))")
    for der in d.derived:
        lines.append(f"df = df.with_columns(({der.expr}).alias({der.name!r}))")
    for f in d.filters:
        lines.append(f"df = df.filter({f})")

    split = d.split
    lines += [
        "",
        "# --------------------------------------------------------------- 2. split",
    ]
    if split.mode == "random":
        lines += [
            f"is_train = np.random.default_rng({split.seed}).random(df.height) < {split.fraction}",
            f"df = df.with_columns(pl.Series({split.column!r}, is_train.astype(np.int64)))",
        ]
    else:
        lines.append(
            f"df = df.with_columns((pl.col({split.column!r}) == {split.train_value!r}).cast(pl.Int64).alias({split.column!r}))"
        )
    lines += [
        f"train = df.filter(pl.col({split.column!r}) == 1)",
        f"holdout = df.filter(pl.col({split.column!r}) == 0)",
        "",
        "# -------------------------------------------------------------- 3. design",
    ]
    ignored = project.exploration.get("leakage", {}).get("ignored", [])
    if ignored:
        lines.append(f"# excluded after the leakage review: {', '.join(ignored)}")
    if run is not None:
        lines.append(_spec_code(run.spec))
        alpha = run.fit.alpha
        chose_by_cv = cfg.penalty.alpha is None
        monotone = dict(run.fit.monotone)
    else:
        dd = project.design.defaults
        lines += [
            "# (fit in the workbench to have every knot and level written out explicitly)",
            "spec = DesignSpec.from_data(",
            f"    train, {cfg.predictors!r},",
            f"    n_bins={dd.n_bins}, min_level_share={dd.min_level_share}, null_indicator={dd.null_indicator},",
            f"    weight_col={cfg.weight!r},",
            ")",
        ]
        alpha = cfg.penalty.alpha if cfg.penalty.alpha is not None else None
        chose_by_cv = False
        monotone = {
            **{
                v: vd.monotone
                for v, vd in project.design.variables.items()
                if vd.monotone
            },
            **cfg.monotone,
        }
    lines += [
        "",
        "# ----------------------------------------------------------------- 4. fit",
    ]
    if alpha is None:
        fit_src = _fit_code(cfg, 0.0, monotone, False).replace(
            "alpha=0.0", f"cv={cfg.penalty.cv}, n_alphas={cfg.penalty.n_alphas}"
        )
    else:
        fit_src = _fit_code(cfg, float(alpha), monotone, chose_by_cv)
    lines += [fit_src, "print(fit)", "print(fit.coef_table(drop_zero=True))"]

    exposure = project.exposure or (cfg.weight if cfg.divide_target_by_weight else None)
    lines += [
        "",
        "# --------------------------------------------------- 5. rate tables & scorer",
        "rm = to_rate_model(",
        "    fit,",
        f"    base={cfg.base!r},",
        f"    base_rate_override={cfg.base_rate_override!r},",
        f"    exposure_col={exposure!r},",
        f"    train_test_col={split.column!r},",
        f"    model_type={cfg.family!r},",
        ")",
    ]
    if cfg.adjustments:
        lines.append("# manual adjustments made in the relativity editor")
        for adj in cfg.adjustments:
            lines.append(
                f"rm.update_relativity({adj.variable!r}, {adj.from_!r}, {adj.to_!r}, {float(adj.relativity)!r})"
            )
        lines.append(
            f'rm.create_snapshot("{len(cfg.adjustments)} manual adjustment(s)")'
        )
    lines += [
        "",
        f"rm.to_json({prefix + '.easyglm'!r})",
        f"rm.to_excel({prefix + '_rate_tables.xlsx'!r})  # adjusted tables, as scored",
        "",
        "holdout_pred = rm.predict(holdout)",
        f"print('holdout A/E:', holdout[{cfg.target!r}].sum() / holdout_pred.sum())",
        "",
    ]
    return "\n".join(lines)
