"""Actuarial check for piece C2 (legacy removal).

Prints the golden French-motor numbers computed by the current code (they must
equal the numbers recorded in ``tests/test_golden.py``) and the size of a base
install before (v0.3.0 tag) and after this piece. Pass ``--write`` to regenerate
``docs/checks/c2-legacy-removal.md``; by default nothing on disk is touched.

Run from the repository root::

    .venv/bin/python scripts/checks/c2_legacy_removal.py [--write]
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
from pathlib import Path

import numpy as np
import polars as pl

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "tests"))

from test_golden import (  # noqa: E402  (imported for the recorded numbers)
    ALPHA,
    FIXTURE,
    GOLDEN,
    PREDICTORS,
    SPLIT_SEED,
)

from easy_glm import DesignSpec, fit_glm, to_rate_model  # noqa: E402
from easy_glm.workflow import (  # noqa: E402
    ModelConfig,
    deviance_stats,
    gini,
    totals,
    unit_values,
)


def _base_dependencies(pyproject_text: str) -> list[str]:
    block = re.search(r"^dependencies = \[(.*?)^\]", pyproject_text, re.S | re.M)
    if block is None:
        return []
    names = re.findall(r'^\s*"([A-Za-z0-9_.-]+)', block.group(1), re.M)
    return names


def _deps_at(ref: str) -> list[str] | None:
    try:
        text = subprocess.run(
            ["git", "show", f"{ref}:pyproject.toml"],
            cwd=ROOT,
            capture_output=True,
            text=True,
            check=True,
        ).stdout
    except (subprocess.CalledProcessError, FileNotFoundError):
        return None
    return _base_dependencies(text)


def compute() -> dict:
    df = pl.read_parquet(FIXTURE)
    rng = np.random.default_rng(SPLIT_SEED)
    df = df.with_columns(
        pl.Series("traintest", (rng.random(df.height) < 0.7).astype(np.int64))
    )
    train = df.filter(pl.col("traintest") == 1)
    holdout = df.filter(pl.col("traintest") == 0)
    spec = DesignSpec.from_data(train, PREDICTORS, weight_col="Exposure")
    fit = fit_glm(
        train,
        spec,
        "ClaimNb",
        family="poisson",
        weight_col="Exposure",
        divide_target_by_weight=True,
        alpha=ALPHA,
    )
    rm = to_rate_model(fit, exposure_col="Exposure", train_test_col="traintest")
    cfg = ModelConfig(
        family="poisson",
        target="ClaimNb",
        weight="Exposure",
        divide_target_by_weight=True,
        predictors=PREDICTORS,
    )
    pred = rm.predict(holdout, exposure_col=None)
    actual, expected, w = totals(holdout, cfg, pred)
    y, wu = unit_values(holdout, cfg)
    dev = deviance_stats(fit.model.family_instance, y, pred, wu)
    return {
        "holdout_ae": float(actual.sum() / expected.sum()),
        "holdout_gini": float(gini(actual, expected, w)),
        "holdout_dev_explained": float(dev["deviance_explained"]),
        "n_nonzero": int((fit.coef != 0).sum()),
        "n_features": int(len(fit.coef)),
        "base_rate": float(rm.base_rate),
        "max_rel_diff_tables_vs_glm": float(
            np.abs(pred / fit.predict(holdout) - 1).max()
        ),
    }


def render(numbers: dict, before: list[str] | None, after: list[str]) -> str:
    def row(label: str, key: str, fmt: str) -> str:
        got = numbers[key]
        gold = GOLDEN[key]
        same = (
            got == gold
            if isinstance(gold, int)
            else abs(got - gold) <= 1e-6 * max(abs(gold), 1e-12)
        )
        return f"| {label} | {format(got, fmt)} | {format(gold, fmt)} | {'yes' if same else 'NO'} |"

    lines = [
        "# C2 — legacy removal: what changed for you",
        "",
        "*Generated by `scripts/checks/c2_legacy_removal.py` on the checked-in 50,000-policy "
        "French motor subsample (`tests/fixtures/french_motor_50k.parquet`).*",
        "",
        "## In one sentence",
        "",
        "Nothing that worked in 0.3 changes its numbers; the old blueprint / DuckDB route "
        "that produced the mis-rated bottom bands in 0.2 is gone for good, and the package "
        "installs with fewer dependencies.",
        "",
        "## What was removed",
        "",
        "- The 0.2-era pipeline (`generate_blueprint`, `prepare_data`, `fit_lasso_glm`, "
        "`ratetable`, `generate_all_ratetables`) and the DuckDB database engine it needed. "
        "Since 0.3 these only existed as deprecated aliases; the workbench and `EasyGLM.fit` "
        "never used them.",
        "- Eight exploratory scripts and a prototype example that only ran against that pipeline.",
        "- `matplotlib` / `seaborn` are no longer installed by default (only needed for the "
        'optional matplotlib charts: `pip install "easy_glm[viz]"`).',
        "",
        "## What is guaranteed",
        "",
        "- A golden test now runs on every code change: it fits a fixed model on the 50k "
        "subsample and compares the numbers below with the recorded values. Any change to a "
        "recorded number blocks a merge until it is explained in writing.",
        "- Hand-built rate tables (from Excel or elsewhere) load through "
        "`RateModel.from_rate_tables` in the same table layout the package exports, and a "
        "table built that way scores identically to the exact tables from the fit.",
        "- The Gini coefficient no longer wobbles in the fifth decimal between identical runs "
        "(ties in predicted rate are now pooled the same way every time).",
        "",
        "## Golden numbers (French motor 50k, holdout, fixed alpha 0.001)",
        "",
        "| Quantity | This run | Recorded | Match |",
        "|---|---|---|---|",
        row("Holdout A/E", "holdout_ae", ".6f"),
        row("Holdout Gini", "holdout_gini", ".6f"),
        row("Holdout deviance explained", "holdout_dev_explained", ".4%"),
        row("Non-zero coefficients", "n_nonzero", "d"),
        row("Design columns", "n_features", "d"),
        row("Base rate", "base_rate", ".6f"),
        "",
        f"Rate tables vs GLM on the holdout: max relative difference below 1e-12 "
        f"(measured {numbers['max_rel_diff_tables_vs_glm']:.1e}).",
        "",
        "## Install footprint (base `pip install easy_glm`)",
        "",
    ]
    if before is not None:
        lines.append(f"- v0.3.0: {len(before)} required packages ({', '.join(before)})")
    lines.append(f"- now: {len(after)} required packages ({', '.join(after)})")
    lines += [
        "",
        "## Questions for you",
        "",
        "None for this piece.",
        "",
    ]
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--write",
        action="store_true",
        help="regenerate docs/checks/c2-legacy-removal.md",
    )
    args = parser.parse_args()
    numbers = compute()
    before = _deps_at("v0.3.0")
    after = _base_dependencies((ROOT / "pyproject.toml").read_text())
    text = render(numbers, before, after)
    print(text)
    mismatches = [
        k
        for k in ("holdout_ae", "holdout_gini", "holdout_dev_explained", "base_rate")
        if abs(numbers[k] - GOLDEN[k]) > 1e-6 * max(abs(GOLDEN[k]), 1e-12)
    ] + [k for k in ("n_nonzero", "n_features") if numbers[k] != GOLDEN[k]]
    if mismatches:
        print(f"\nGOLDEN MISMATCH: {mismatches}", file=sys.stderr)
        sys.exit(1)
    if args.write:
        out = ROOT / "docs" / "checks" / "c2-legacy-removal.md"
        out.write_text(text)
        print(f"\nwritten {out}")


if __name__ == "__main__":
    main()
