"""Plain-language record of the README release gate (piece R11).

Runs exactly what ``tests/test_readme.py`` runs — every ```python block on
``README.md``, in order, in one namespace, plus every ``examples/*.py`` as a
subprocess — and times it, so the actuary-facing document in
``docs/checks/readme-gate.md`` is a real result, not a claim: "every block
ran, on this date, on this Python, in this many seconds" is generated from an
actual run, never typed by hand.

Run from the repository root::

    .venv/bin/python scripts/checks/readme_gate.py [--write]
"""

from __future__ import annotations

import argparse
import platform
import re
import subprocess
import sys
import tempfile
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
README = ROOT / "README.md"
DOC = ROOT / "docs" / "checks" / "readme-gate.md"
EXAMPLES = sorted((ROOT / "examples").glob("*.py"))

_BLOCK_RE = re.compile(r"```python( skip-test)?\n(.*?)```", re.DOTALL)


def extract_blocks() -> list[tuple[bool, str]]:
    text = README.read_text(encoding="utf-8")
    return [(bool(flag), code) for flag, code in _BLOCK_RE.findall(text)]


def run_readme_blocks(blocks: list[tuple[bool, str]], workdir: Path) -> float:
    """Run every non-skip block in one namespace, chdir'd to ``workdir`` with
    ``tests/fixtures`` linked in; returns the elapsed seconds. Raises on the
    first block that fails, exactly like the test does."""
    fixtures = workdir / "tests" / "fixtures"
    fixtures.parent.mkdir(parents=True, exist_ok=True)
    fixtures.symlink_to(ROOT / "tests" / "fixtures")

    import os

    cwd = os.getcwd()
    os.chdir(workdir)
    try:
        namespace: dict = {}
        t0 = time.perf_counter()
        for i, (skip, code) in enumerate(blocks):
            if skip:
                continue
            exec(compile(code, f"<README.md block {i}>", "exec"), namespace)
        return time.perf_counter() - t0
    finally:
        os.chdir(cwd)


def run_examples() -> list[tuple[str, float, int]]:
    """``(name, seconds, returncode)`` for every examples/*.py, each in its
    own temp working directory."""
    results = []
    for example in EXAMPLES:
        with tempfile.TemporaryDirectory() as tmp:
            t0 = time.perf_counter()
            proc = subprocess.run(
                [sys.executable, str(example)],
                cwd=tmp,
                capture_output=True,
                text=True,
                timeout=180,
            )
            results.append((example.name, time.perf_counter() - t0, proc.returncode))
    return results


def main(write: bool) -> None:
    blocks = extract_blocks()
    n_run = sum(1 for skip, _ in blocks if not skip)
    n_skip = sum(1 for skip, _ in blocks if skip)

    with tempfile.TemporaryDirectory() as tmp:
        readme_seconds = run_readme_blocks(blocks, Path(tmp))
    example_results = run_examples()
    failed = [r for r in example_results if r[2] != 0]
    total_seconds = readme_seconds + sum(r[1] for r in example_results)

    py = platform.python_version()
    today = time.strftime("%Y-%m-%d")

    lines = [
        "# The README release gate, in plain language",
        "",
        f"*Generated by `scripts/checks/readme_gate.py --write` on {today}, "
        f"Python {py}.*",
        "",
        "## What this proves",
        "",
        "Every code block on the front page of this repository — the one a "
        "new user reads first — actually runs, in the order it is shown, "
        "against the checked-in sample of the data. This is checked by a "
        "test (`tests/test_readme.py`), which runs in the normal test suite "
        "and therefore in CI on every change: if a README block stops "
        "working, the build goes red, the same as a broken feature would.",
        "",
        f"**Last run: {n_run} python blocks from README.md and "
        f"{len(EXAMPLES)} scripts in `examples/` all ran without error, "
        f"on {today}, on Python {py}, in {total_seconds:.0f} seconds "
        "in total** ({readme_seconds:.0f}s for the README, "
        f"{total_seconds - readme_seconds:.0f}s for the examples).".format(
            readme_seconds=readme_seconds, total_seconds=total_seconds
        ),
        "",
        f"{n_skip} block(s) on the README are marked as needing a browser or "
        "the workbench's own server (opening the relativity editor) and are "
        "not run here — the test caps how many blocks may claim that "
        "exemption, so it cannot be used to quietly skip something that "
        "should work.",
        "",
        "## The examples",
        "",
        "| Script | Seconds | Result |",
        "|---|---:|---|",
    ]
    for name, seconds, code in example_results:
        lines.append(
            f"| `examples/{name}` | {seconds:.1f} | {'OK' if code == 0 else 'FAILED'} |"
        )

    lines += [
        "",
        "## What would make this fail",
        "",
        "- A code change to `easy_glm` that breaks a call shown on the "
        "README (a renamed argument, a changed default, a removed function).",
        "- A README edit that adds a new code block with a mistake in it "
        "(a typo, a variable used before it is defined, a call that no "
        "longer matches the library).",
        "- A new `examples/*.py` script that does not run standalone.",
        "",
        "None of this needs a network connection: every example reads the "
        "50,000-row French motor sample checked into "
        "`tests/fixtures/french_motor_50k.parquet`, or generates its own "
        "synthetic data.",
        "",
    ]
    if failed:
        lines.insert(0, "**THIS RUN FAILED** — see below.\n")
        for name, _seconds, code in failed:
            lines.append(f"- `examples/{name}` exited {code}")

    text = "\n".join(lines)
    print(text, end="")
    if write:
        DOC.write_text(text)
        print(f"\nwritten: {DOC}")

    if failed:
        raise SystemExit(1)


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument(
        "--write", action="store_true", help="regenerate the docs/checks document"
    )
    main(ap.parse_args().write)
