"""Actuarial check for piece W1 — workbench state: exploration sample vs
full-data fits (D2) and persisted fitted runs (D1).

Runs the workbench's own state helpers inside Streamlit's test harness on the
French-motor fixture and prints, in plain language, what an actuary can rely on:

(a) with an exploration sample set, the fit still uses every training row;
(b) after a simulated browser reload the fit is restored with identical
    predictions;
(c) changing the data file invalidates the persisted fit.

Usage: python scripts/checks/w1_state.py [--write]
  --write regenerates docs/checks/w1-state.md; otherwise the document is printed.
"""

from __future__ import annotations

import argparse
import os
import shutil
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
FIXTURE = ROOT / "tests" / "fixtures" / "french_motor_50k.parquet"
DOC = ROOT / "docs" / "checks" / "w1-state.md"
SAMPLE = 10_000
PREDICTORS = ["DrivAge", "VehAge", "BonusMalus", "Density", "VehPower", "Region"]


def _script(project_path: str, body: str) -> str:
    return f"""
import numpy as np
import polars as pl
import streamlit as st
from easy_glm.app import state as S
from easy_glm.workflow import Project

S.init_state()
if not st.session_state.get("_loaded"):
    S.set_project(Project.from_json({project_path!r}), {project_path!r})
    st.session_state._loaded = True
p = S.project()
out = {{}}
{body}
st.session_state["out"] = out
"""


def _run(script: str) -> dict:
    from streamlit.testing.v1 import AppTest

    at = AppTest.from_string(script, default_timeout=600)
    at.run()
    if at.exception:
        raise RuntimeError([e.value for e in at.exception])
    return at.session_state["out"]


def main(write: bool) -> int:
    if not FIXTURE.exists():
        print(f"fixture missing: {FIXTURE}")
        return 1
    from easy_glm.workflow import Project

    work = Path(tempfile.mkdtemp(prefix="w1_check_"))
    data = work / "french_motor_50k.parquet"
    shutil.copy(FIXTURE, data)
    p = Project(name="w1check")
    p.data.source.type = "parquet"
    p.data.source.path = str(data)
    p.data.roles = {
        "ClaimNb": "target",
        "Exposure": "weight",
        "IDpol": "id",
        **dict.fromkeys(PREDICTORS, "predictor"),
    }
    p.data.split.mode = "random"
    p.data.split.column = "traintest"
    p.data.split.seed = 42
    p.data.sample_rows = SAMPLE
    p.new_model("freq", divide_target_by_weight=True)
    p.models["freq"].penalty.alpha = 0.001
    p.models["freq"].penalty.cv = None
    project = work / "w1check.easyglm-project.json"
    p.to_json(project)
    pred_path = work / "pred.parquet"

    # (a) sample vs full, and persist
    a = _run(
        _script(
            str(project),
            f"""
full = S.prepared_frame(); sample = S.sample_frame(); train = S.train_frame()
run = S.fit_model("freq")
hold = full.filter(pl.col("traintest") == 0)
pl.DataFrame({{"pred": run.predict(hold)}}).write_parquet({str(pred_path)!r})
out["rows"] = full.height; out["sample"] = sample.height; out["train"] = train.height
out["run_train_rows"] = run.train_rows; out["holdout"] = hold.height
out["files"] = [f.name for f in sorted(S.runs_dir().glob("*.pkl"))]
out["ae"] = run.metrics["holdout"]["ae"]; out["gini"] = run.metrics["holdout"]["gini"]
""",
        )
    )
    # (b) reload
    b = _run(
        _script(
            str(project),
            f"""
import time
t0 = time.perf_counter()
run = S.get_run("freq")
out["restored"] = run is not None
out["seconds"] = round(time.perf_counter() - t0, 2)
hold = S.prepared_frame().filter(pl.col("traintest") == 0)
ref = pl.read_parquet({str(pred_path)!r})["pred"].to_numpy()
out["max_abs_diff"] = float(np.abs(run.predict(hold) - ref).max())
""",
        )
    )
    # (c) data change
    os.utime(data, (1_000_000_000, 1_000_000_000))
    c = _run(
        _script(
            str(project),
            """
out["restored"] = S.get_run("freq") is not None
out["files"] = [f.name for f in sorted(S.runs_dir().glob("*.pkl"))] if S.runs_dir().exists() else []
""",
        )
    )

    lines = [
        "# W1 — workbench state: what changed for you",
        "",
        "*Generated by `scripts/checks/w1_state.py` on the French-motor fixture "
        f"({a['rows']:,} policies, seeded 70/30 split).*",
        "",
        "## Two things the workbench now guarantees",
        "",
        "1. **The exploration sample never touches the fit.** The Project page "
        "has an *exploration sample* setting that only speeds up the Explore "
        "page and the preview charts on the Design and Variables pages. Fits, "
        "diagnostics, rate tables, the leakage report, and the knots and levels "
        "of every rating factor always use the full data. In 0.3 the sample "
        "applied to everything, so a model fitted while exploring on a sample "
        "was a model of the sample.",
        "2. **A fitted model survives a browser refresh and reopening the project.** "
        "Each fit is stored next to the project file (a folder ending in "
        "`.easyglm-runs`). It is only reused when the model specification, the "
        "data file (path, size, last-modified time) and the software versions "
        "are all unchanged; otherwise it is discarded and the model is refitted. "
        "Manual adjustments and the base-rate override are always re-applied "
        "from the project file, which remains the single source of truth. An "
        "unsaved project persists nothing (the sidebar says so).",
        "",
        "## Numbers from this run",
        "",
        "| Quantity | Value |",
        "|---|---|",
        f"| Policies in the file | {a['rows']:,} |",
        f"| Exploration sample used by the Explore page | {a['sample']:,} rows |",
        f"| Training rows available | {a['train']:,} |",
        f"| Training rows used by the fit | {a['run_train_rows']:,} |",
        f"| Holdout A/E · Gini | {a['ae']:.4f} · {a['gini']:.4f} |",
        f"| Persisted fit files after fitting | {len(a['files'])} |",
        f"| Fit restored after a simulated reload | {'yes' if b['restored'] else 'no'} ({b['seconds']} s) |",
        f"| Max difference in restored holdout predictions | {'0 (identical)' if b['max_abs_diff'] == 0 else b['max_abs_diff']:} |",
        f"| Fit restored after the data file changed | {'yes' if c['restored'] else 'no'} |",
        f"| Persisted fit files after the data change | {len(c['files'])} |",
        "",
        "## What to check yourself",
        "",
        "Set an exploration sample on the Project page, fit, and compare the "
        "training-row count shown under the fit with the row count in the "
        "Project page preview: they must match the full data. Refresh the "
        "browser: the Model page must still show the fit without refitting.",
        "",
        "## Questions for you",
        "",
        "None for this piece.",
        "",
    ]
    text = "\n".join(lines)
    ok = (
        a["run_train_rows"] == a["train"]
        and a["sample"] == SAMPLE
        and b["restored"]
        and b["max_abs_diff"] == 0
        and not c["restored"]
        and not c["files"]
    )
    if write:
        DOC.write_text(text)
        print(f"wrote {DOC}")
    else:
        print(text)
    shutil.rmtree(work, ignore_errors=True)
    print("CHECK PASSED" if ok else "CHECK FAILED")
    return 0 if ok else 2


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--write", action="store_true")
    sys.exit(main(ap.parse_args().write))
